# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.7"

node_js:
  - "node"

install:
  - pip install poetry
  - poetry install
  - yarn

script:
  - poetry run py.test tests
