services:
  dribdat:
    image: dribdat
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - SERVER_URL=localhost.changeme:5000
      - DATABASE_URL=postgres://dribdat_user:changeme@db:5432/dribdat
      - DRIBDAT_ENV=prod
      - DRIBDAT_SECRET=changeme
      - DRIBDAT_APIKEY=changeme
      - TIME_ZONE=Europe/Zurich
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dribdat
      - POSTGRES_USER=dribdat_user
      - POSTGRES_PASSWORD=changeme
